### ISSUE TITLE
Version v5.1.5 seemingly not compatible with React-Leaflet v2

### ISSUE THREAD

**Issue by FredChauviere** [TA-Geoforce/react-leaflet-google-v2#16]
Got some 
"Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>"

It worked again if I rollback to the 5.1.3 version

I know release notes say that it has been tested with react-leaflet v3, but I think it should have been versioned as v6 since there's breaking change. Especially since the module is called react-leaflet-google-**v2**, you kind of expect it still works with react-leaflet v2...

**Comment by Mylothros-Charalampos** [comment]
hello @FredChauviere, sorry for the late reply, we were investigating the error you mentioned and we published a new version can you try the version 5.2.0, use react leaflet 3.0.5 and tell us if everything is okay now?

**Comment by FredChauviere** [comment]
Sorry for the delay: exactly same error with react-leaflet-google-v2 5.2.0 and react-leaflet 2.8.0...
I can't migrate to react-leaflet v3.0.5, there's too much breaking code...

**Comment by Mylothros-Charalampos** [comment]
hello @FredChauviere the error you are speaking of persist because v5.2.0 is not compatible with react-leaflet < v3, because migrations have been made in react-leaflet-google-v2 for react-leaflet-v3 so if you want to continue using in your project 
react-leaflet-google-v2 you will have to roll back to a version it was compatible with react-leaflet-v2 like  5.1.3 if I am not mistaken.

**Comment by FredChauviere** [comment]
Yeak, I know now (after trial and error). I was just pointing the facts that :

- that migration should have been flagged as code breaking during 5.1.4 version development and so should have been designated as a 6.X version.
- that migration could even have been the object of a new project since react-leaflet-google-v2 got **v2** in its name, and is now not compatible with react-leaflet-**v2**....

**Comment by Mylothros-Charalampos** [comment]
thanks for pointing it out we will  make a new release soon. :)
