### ISSUE TITLE
Why V2?

### ISSUE THREAD

**Issue by aqueiros** [TA-Geoforce/react-leaflet-google-v2#4]
Greetings. I have been using react-leaflet-google on an old project and now that I was about to create another one I notice that react-leaflet-google was archived and now this one here exists. It would be nice to know the motivation behind the fork and if in general it's a better idea to use this V2 instead of the old one. Thanks!

**Comment by Charmatzis** [comment]
yes, V2 is the current version which is supported, and it is under another domain, so we can work on improvements.
