### ISSUE TITLE
TypeError: Cannot read property 'off' of undefined

### ISSUE THREAD

**Issue by chrisdonnelly** [TA-Geoforce/react-leaflet-google-v2#6]
Using react-leaflet-google-v2@5.1.3 with react-leaflet@2.8.0 and leaflet@1.7.1

API key and version is correct and returns 200 response.  

Type error occurs in LayerControl.

<img width="362" alt="Screenshot 2021-04-23 at 12 55 46" src="https://user-images.githubusercontent.com/29203252/115867843-7ea59400-a433-11eb-99a7-6379b1580cd6.png">
<img width="704" alt="Screenshot 2021-04-23 at 12 54 47" src="https://user-images.githubusercontent.com/29203252/115867852-81a08480-a433-11eb-9d9b-121308432b27.png">
<img width="1259" alt="Screenshot 2021-04-23 at 12 33 17" src="https://user-images.githubusercontent.com/29203252/115868118-da701d00-a433-11eb-948b-e218632bd8b7.png">

**Comment by Mylothros-Charalampos** [comment]
thank you for your report of the issue could you please try to recreate the problem, because the repo is updated. Download the repo from GitHub and recreate the problem it is not published yet.

**Comment by Mylothros-Charalampos** [comment]
thank you for your report could you please create and post an example-repo with the problem, or try to re-create the problem by using our latest version?
